api_v0/tracker/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from api_v0.tracker.views import set_serializer_view, trainunit_serializer_view
from api_v0.tracker.views import exerciseunit_serializer_view

# Serializer Urls:
urlpatterns = [
    url(r'^set_list_rest/$', set_serializer_view.SetList.as_view(), name='set_list'),
    url(r'^set_detail_rest/(?P<pk>[0-9A-Fa-f-]+)$', set_serializer_view.SetDetail.as_view(), name='set_detail'),
    url(r'^set_exerciseunit_rest/(?P<exercise_unit>[0-9A-Fa-f-]+)$',
        set_serializer_view.SetListByExerciseUnit.as_view(), name='set_exerciseunit_list'),

    url(r'^exerciseunit_list_rest/$', exerciseunit_serializer_view.ExerciseUnitList.as_view(), name='exerciseunit_list'),
    url(r'^exerciseunit_detail_rest/(?P<pk>[0-9A-Fa-f-]+)$', exerciseunit_serializer_view.ExerciseUnitDetail.as_view(),
        name='exerciseunit_detail'),
    url(r'^exerciseunit_trainunit_rest/(?P<train_unit>[\w\-]+)$',
        exerciseunit_serializer_view.ExerciseUnitListByTrainUnit.as_view(), name='exerciseunit_trainunit_list'),

    url(r'^trainunit_list_rest/$', trainunit_serializer_view.TrainUnitList.as_view(),
        name='trainunit_list'),
    url(r'^trainunit_detail_rest/(?P<pk>[0-9A-Fa-f-]+)$', trainunit_serializer_view.TrainUnitDetail.as_view(),
        name='trainunit_detail'),
    url(r'^trainunit_user_rest/(?P<user>[\w\-]+)$',
        trainunit_serializer_view.TrainUnitListByUserId.as_view(), name='trainunit_user_list'),
]

app_tracker/urls/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from app_tracker import views

urlpatterns = [
    url(r'^training_units/(?P<pk>\d+)$', views.TrainingUnitsList.as_view(), name='training_units'),
    url(r'^exercise_unit_list/(?P<pk>[0-9A-Fa-f-]+)$', views.ExerciseUnitList.as_view(), name='exercise_unit_list'),
    url(r'^exercise_unit_list/(?P<pk>[0-9A-Fa-f-]+)/add/$', views.AddExerciseUnit.as_view(), name='add_exercise_unit'),
    url(r'^training_units/(?P<pk>[0-9A-Fa-f-]+)/delete/$', views.DeleteTrainingUnit.as_view(),
        name='delete_training_unit'),
]

gimprove/urls.py
"""gimprove URL Configuration

The `urlpatterns` list routes URLs to views.
"""
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns
from app_tracker.consumers.SetConsumer import SetConsumer
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as rest_framework_views

urlpatterns = i18n_patterns(
    url(r'^landing_page/', include('app_landingpage.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', RedirectView.as_view(url='/landing_page/', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^tracker/', include('app_tracker.urls.urls')),
    url(r'^api_v0_tracker/', include('api_v0.app_tracker.urls')),
    url(r'^api_v0_main/', include('api_v0.app_main.urls')),
    url(r'^/ws/tracker', SetConsumer),
    url(r'^docs/', include_docs_urls(title='Gimprove Api', authentication_classes=[],
                                     permission_classes=[]))
]

urlpatterns += [
    url(r'^get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^contact$', views.contact, name='contact'),
    url(r'^about$', views.about, name='about'),
    url(r'^activities/(?P<pk>\d+)$', views.ActivityListView.as_view(), name='activities'),
    url(r'^training_units/(?P<pk>\d+)$', views.TrainingUnitsList.as_view(), name='training_units'),
    url(r'^exercise_unit_list/(?P<pk>[0-9A-Fa-f-]+)$', views.ExerciseUnitList.as_view(), name='exercise_unit_list'),
    url(r'^exercise_unit_list/(?P<pk>[0-9A-Fa-f-]+)/add/$', views.AddExerciseUnit.as_view(), name='add_exercise_unit'),
    url(r'^exercise_unit_list/(?P<pk>[0-9A-Fa-f-]+)/delete/$', views.DeleteTrainingUnit.as_view(),
        name='delete_training_unit'),
    url(r'^user_profile/(?P<pk>\d+)$', views.UserProfileView.as_view(), name='profile'),
    url(r'^achievements/(?P<pk>\d+)$', views.AchievementView.as_view(), name='achievements'),
    url(r'^gym/(?P<pk>\d+)$', views.GymView.as_view(), name='gym'),
    url(r'^followers/(?P<pk>\d+)$', views.FollowerView.as_view(), name='followers'),
    url(r'^profile/cre_connection/(?P<pk>\d+)$', views.create_connection, name='create_connection'),
    url(r'^profile/del_connection/(?P<pk>\d+)$', views.delete_connection, name='delete_connection'),
]

# Serializer Urls:
urlpatterns += [
    url(r'^set_list_rest/$', views.SetList.as_view(), name='set_list'),
    url(r'^set_detail_rest/(?P<pk>[0-9A-Fa-f-]+)$', views.SetDetail.as_view(), name='set_detail'),
    url(r'^userprofile_detail_rest/(?P<pk>[0-9A-Fa-f-]+)$', views.UserProfileDetail.as_view(),
        name='userprofile_detail'),
    url(r'^userprofile_detail_rfid_rest/(?P<rfid_tag>[\w\-]+)$', views.UserProfileDetailByRfid.as_view(),
        name='userprofile_rfid_detail')
]

app_tracker/models/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
import uuid
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from datetime import timedelta
import json
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from app_main.models.models import UserProfile
from django.db.models.signals import post_delete, pre_delete


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class UserTrackingProfile(models.Model):
    user_profile = models.ForeignKey('app_main.UserProfile', on_delete=models.CASCADE)
    _pr_active_set = models.ForeignKey('app_tracker.Set', blank=True, null=True, on_delete=models.DO_NOTHING)

    @property
    def active_set(self):
        """
        Returns active set. If set has not been changed during the last 15 seconds, returns None.
        """
        if self._pr_active_set is not None:
            time_diff = timezone.now() - self._pr_active_set.last_update
            if time_diff.seconds > 15:
                self._pr_active_set = None
        return self._pr_active_set

    @active_set.setter
    def active_set(self, a_set):
        self._pr_active_set = a_set

    def __str__(self):
        return str(self.user_profile.user)


class ClientConnection(models.Model):
    """
    Represents a connection from a client to the server. Created and used by the SetConsumer-Class for example.
    """
    name = models.CharField(max_length=40, primary_key=True, blank=False, null=False)
    user = models.CharField('user', max_length=10, blank=False, null=False)


class Exercise(models.Model):
    """
    Represents an executable exercise (not a group of sets!).
    """
    name = models.CharField(max_length=100, primary_key=True)
    description = models.CharField(max_length=1000, help_text="Insert short description here.")
    muscles = models.ManyToManyField('Muscle', help_text="Muscles trained by the exercise.")
    equipment_machine = models.ManyToManyField('Equipment', help_text="Necessary equipment for the exercise.", blank=True)
    gimprove_system = models.BooleanField(blank=False, null=False, default=False)
    # TODO: Auto-fill equipment machine when a new equipment for this exercise is created!

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('exercise-detail', args=[str(self.name)])


class MuscleGroup(models.Model):
    name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.name


class Muscle(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    muscle_group = models.ForeignKey(MuscleGroup, on_delete=models.DO_NOTHING, null=False, blank=False)

    def __str__(self):
        return self.name


class TrainUnit(models.Model, LoginRequiredMixin):
    """
    Represents a group of exercise units executed together at a specific point of time.
    """
    login_url = '/login/'
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    start_time_date = models.DateTimeField(default=timezone.now, null=False, blank=False)
    end_time_date = models.DateTimeField(default=timezone.now, null=False, blank=False)
    date = models.DateField(null=False, blank=False)
    user = models.ForeignKey(UserTrackingProfile, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-start_time_date']

    def __str__(self):
        return str(timezone.localtime(self.start_time_date)) + " - " + str(timezone.localtime(self.end_time_date))

    def get_absolute_url(self):
        return reverse('exercise_unit_list', args=[str(self.id)])

    def clean(self):
        if self.start_time_date >= self.end_time_date:
            raise ValidationError('End time must be after start time!')


class Equipment(models.Model):
    """
    Represents a unique machine within a studio.
    """
    user = models.ForeignKey(User, related_name="user", on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    exercises = models.ManyToManyField(Exercise, blank=False)
    gym = models.ForeignKey('app_main.GymProfile', related_name="gym", on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.gym) + ": " + str(self.id)[0:5]


class ExerciseUnit(models.Model):
    """
    Represents a group of sets of the same exercise within the same TrainUnit.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    time_date = models.DateTimeField(default=timezone.now, null=False, blank=False)
    train_unit = models.ForeignKey(TrainUnit, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-time_date']

    def __str__(self):
        return str(self.exercise) + " " + str(timezone.localtime(self.time_date))

    def clean(self):
        if not ((self.time_date >= self.train_unit.start_time_date) and
                (self.time_date <= self.train_unit.end_time_date)):
            raise ValidationError("Time Date must be within End and Start time of TrainUnit.")


class Set(models.Model):
    """
    Represents a group of repetitions of the same exercise, directly executed one after the other.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    date_time = models.DateTimeField(default=timezone.now, null=False, blank=False)
    exercise_unit = models.ForeignKey(ExerciseUnit, blank=True, null=True, on_delete=models.CASCADE, default=None)
    equipment = models.ForeignKey(Equipment, blank=True, null=True, on_delete=models.DO_NOTHING)
    exercise = models.ForeignKey(Exercise, blank=True, null=True, on_delete=models.CASCADE, default=None)
    repetitions = models.IntegerField(blank=False)
    weight = models.FloatField(blank=False)
    durations = models.TextField(max_length=1200, blank=False, null=False)
    auto_tracking = models.BooleanField(blank=False, null=False, default=False)
    rfid = models.CharField(max_length=10, blank=True, null=True, default=None)
    last_update = models.DateTimeField(default=timezone.now, null=False, blank=False)
    active = models.BooleanField(default=False, null=False, blank=False)

    class Meta:
        ordering = ['-date_time']

    def __str__(self):
        return str(timezone.localtime(self.date_time)) + "_" + str(self.repetitions) + "r_" + str(self.id)[0:5]

    def get_durations(self):
        return json.loads(self.durations)

    def clean(self):
        # Either at least exercisename & rfid or exerciseunit must be provided and valid
        if self.exercise_unit is None and (self.exercise is None or self.rfid is None):
            raise ValidationError("Either at least exercisename & rfid or exerciseunit must be provided")
        # check exerciseunit
        if self.exercise_unit is not None and len(ExerciseUnit.objects.filter(id=self.exercise_unit.id)) == 0:
            raise ValidationError("Not a valid exercise_unit")
        if self.exercise_unit is not None and ExerciseUnit.objects.get(id=self.exercise_unit.id).time_date > self.date_time:
            raise ValidationError("Set cannot have a date before it's exerciseunit")
        # check rfid
        if self.rfid is not None and len(UserProfile.objects.filter(rfid_tag=self.rfid)) == 0:
            raise ValidationError("Not a valid rfid")
        # check exercise
        if self.exercise is not None and len(Exercise.objects.filter(name=self.exercise.name)) == 0:
            raise ValidationError("Not a valid exercisename")
        # check repetitions
        if (self.repetitions < 0) or (self.repetitions > 500):
            raise ValidationError("Not a reasonable value for repetitions.")
        # check date: must be in the past
        if self.date_time > timezone.now():
            raise ValidationError("Date and time must be in the past.")
        # check weight
        if self.weight < 0:
            raise ValidationError("No negative values allowed for weight.")
        # check whether set date fits the exercise unit date
        if self.exercise_unit is not None:
            if not ((self.exercise_unit.time_date <= self.date_time) &
                    (self.date_time <= (self.exercise_unit.time_date + timedelta(days=1)))):
                raise ValidationError("Date value does not fit to exercise unit.")
        # check whether number of durations and repetitions fit
        if len(json.loads(self.durations)) != self.repetitions:
            raise ValidationError("Number of durations values and repetitions do not fit.")

    def save(self, *args, **kwargs):
        """
        Handles the creation of a new set.
        If there is no exerciseunit specified, check for a trainunit of the specified day first. If there is none,
        create a new trainunit and also a new exerciseunit within this new trainunit. Otherwise, check if there is
        a exerciseunit in the existing trainunit whose exercise matches the one of the set. If not, create a new one.
        Assign the set to the corresponding exerciseunit.
        """
        self.clean()

        # Create a new TrainUnit and ExerciseUnit if necessary.
        if self.exercise_unit is None:
            user_profile = UserProfile.objects.get(rfid_tag=self.rfid)
            user_tracking_profile = UserTrackingProfile.objects.get(user_profile=user_profile)
            # If there already exists a TrainUnit for this day, update the end_time_date-field.
            if TrainUnit.objects.filter(date=self.date_time, user=user_tracking_profile).exists():

api_v0/app_tracker/views/exerciseunit_serializer_view.py
from rest_framework import generics
from api_v0.app_tracker.serializers.ExerciseUnitSerializer import ExerciseUnitSerializer
from app_tracker.models.models import UserTrackingProfile, TrainUnit, ExerciseUnit
from app_main.models.models import UserProfile


class ExerciseUnitList(generics.ListAPIView):
    """
    Class for creating new sets or retrieving a list of sets.
    """
    serializer_class = ExerciseUnitSerializer

    def get_queryset(self):
        user = self.request.user
        userprofile = UserProfile.objects.get(user=user)
        user_tracking_profile = UserTrackingProfile.objects.get(user_profile=userprofile)
        trainunits = TrainUnit.objects.filter(user=user_tracking_profile)
        exerciseunits = ExerciseUnit.objects.filter(train_unit__in=trainunits)
        return exerciseunits


class ExerciseUnitDetail(generics.RetrieveDestroyAPIView):
    """
    View to retrieve or delete ExerciseUnits via http request.
    """
    # TODO: Check for user
    queryset = ExerciseUnit.objects.all()
    serializer_class = ExerciseUnitSerializer


class ExerciseUnitListByTrainUnit(generics.ListAPIView):
    """
    View to retrieve ExerciseUnits by TrainUnit.
    """
    # TODO: Check for user
    queryset = ExerciseUnit.objects.all()
    serializer_class = ExerciseUnitSerializer
    lookup_field = 'train_unit'

app_tracker/templates/tracker/User/training_units.html
{% extends base_template %}

{% block extra_head %}
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

{% endblock %}

{% block site_content %}
<div class="container background-col">
    <div class="row full-height">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-0">
            <div class="row row-eq-height">
                <h1>Meine Workouts</h1>
            </div>
        </div>

        <!-- List of TrainingUnits and the related ExerciseUnits and Sets. -->
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% for train_unit in training_units %}
                <div class="row">
                    <h2>Workout vom {{ train_unit.date }}</h2>
                    {% for exercise_unit in train_unit.exercise_units.all %}
                        <h3>{{ exercise_unit.exercise }}</h3>
                        {% for set in exercise_unit.set_set.all %}
                            <p>Set {{ forloop.counter }}: {{ set.repetitions }} Wiederholungen; {{ set.weight }} kg</p>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app_tracker/templates/tracker/User/user_activitylist.html
{% extends base_template %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'tracker/css/User/user_activities.css' %}">
<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

{% endblock %}

{% block site_content %}
<div class="container background-col">

    <!-- Hand context variables to JS -->
    <script type="text/javascript">
        var profile = "{{ profile }}"
        var user_id = "{{ user_id }}"
        var active_set = "{{ profile.active_set }}";
        var ex_name = "{{ profile.active_set.exercise_unit.exercise }}";
    </script>

    <!-- Actual training activity if available -->
    <div id="active_set_div">
        <div class="row row-eq-height">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-0">
                <h1 id="exercise_name">Active Workout: </h1>
            </div>
        </div>
        <div class="row row-eq-height">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 active_workout">
                <div class="row text-center">
                     <h2>Wiederholungen:</h2>
                </div>
                <div class="row text-center extra-large">
                    <h2 class="extra-large" id="repetitions"></h2>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 active_workout">
                <div class="row text-center">
                     <h2>Gewicht in kg:</h2>
                </div>
                <div class="row text-center">
                    <h2 class="extra-large" id="weight"></h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Network Activities -->
    <div class="row full-height">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-0">
            <div class="row row-eq-height">
                <h1>Neuigkeiten</h1>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 home">
            {% for activity in user.profile.get_follows_activities %}
                <div class="row activity">
                    <h5 class="small-annotation">{{ activity.created }}</h5>
                    <a href="{% url 'profile' activity.user.id %}">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                            <img src="{{ activity.user.profile.profile_image.url }}">
                            <h3>{{ activity.user.username }}</h3>
                        </div>
                    </a>
                    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 ">
                        <p>{{ activity.description }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block js_imports %}
<!-- <script src="{% static 'tracker/js/user_activities.js' %}"></script> -->
{% endblock %}

app_tracker/templates/tracker/User/user_profile.html
{% extends base_template %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

{% endblock %}

{% block site_content %}
<div class="container background-col">
    <div class="row full-height">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-0">

            <div class="row row-eq-height">
                {% if profile.user == user %}
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h1>Mein Profil</h1>
                    </div>
                {% else %}
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hcenter">
                        <h1>{{ profile.user.username }}'s Profil</h1>
                    </div>
                {% endif %}
            </div>

            <!-- Main Information -->
            <div class="row text-center row-eq-height sm-row-padding">
                <!-- Picture and follow button -->
                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 full-h">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 full-width">
                            {% if profile.profile_image %}
                                <img src='{{ profile.profile_image.url  }}' class="profile-img img-resize" alt="Profile Image"/>
                            {% else %}
                                <p>Kein Bild vorhanden.</p>
                            {% endif %}
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 full-width">
                            {% if not profile.user == user and profile.user.id in user.profile.get_follow_ids %}
                                <a href="{% url 'delete_connection' profile.user.id %}"><button type="button" class="btn" >Nicht mehr folgen</button></a>
                            {% elif not profile.user == user %}
                                <a href="{% url 'create_connection' profile.user.id %}"><button type="button" class="btn btn-primary">Folgen</button></a>
                            {% else %}
                                <a></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- Follower -->
                <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
                    <a href="{% url 'followers' profile.user.id %}" class="text-center black-text">
                        <button type="button" class="btn" aria-label="Left Align">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </button>
                        <h3><b>{{ zzprofile.get_follower_connections |length }}<br>Follower</b></h3>
                    </a>
                </div>
                <!-- Follows -->
                <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
                    <a href="{% url 'followers' profile.user.id %}" class="text-center black-text">
                        <button type="button" class="btn" aria-label="Left Align">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </button>
                        <h3><b>{{ profile.get_follows_connections |length }}<br>Abonnements</b></h3>
                    </a>
                </div>
                <!-- Achievements -->
                <div class="col-xs-4 cglyol-sm-4 col-md-2 col-lg-2">
                    <a href="#" class="text-center black-text">
                        <button type="button" class="btn" aria-label="Left Align">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        </button>
                        <h3><b>{{ profile.achievements.all |length }}<br>Erfolge</b></h3>
                    </a>
                </div>
            </div>
            <!-- Description -->
            {% if profile.bio %}
                <div class="row text-center sm-row-padding">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <p>{{ profile.bio }}</p>
                    </div>
                </div>
            {% endif %}
            <!-- Gym -->
            {% if profile.gym %}
                <div class="row text-center sm-row-padding">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <p><b>Gym: </b>
                                {% for gym in profile.gym.all %}
                                    {{ gym }}
                                {% endfor %}
                            </p>
                    </div>
                </div>
            {% endif %}
            <div class="row sm-row-padding">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    {% if profile.user == user %}
                        <h2>Meine Erfolge:</h2>
                    {% else %}
                        <h2><b>{{ profile.user.username }}'s Erfolge:</b></h2>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% for achievement in profile.achievements.all %}
                    {% if achievement.achievement_image %}
                        <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
                            <img class="img-responsive" src="{{ achievement.achievement_image.url }}">
                            <p class="text-center">{{ achievement.description }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_tracker/templates/tracker/User/user_tracker_base.html
{% extends "tracker/tracker_base.html" %}

{% block sidebar_content %}
                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="{% url 'activities' user.id %}">general</a>
                    </div>
                </li>

                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="#training-subnav" data-toggle="collapse" aria-expanded="false">Training</a>
                    </div>
                    <ul class="sidebar-subnav collapse" id="training-subnav">
                        <li class="sidebar-subcategory"><a href="">overview</a></li>
                        <li class="sidebar-subcategory"><a href="{% url 'training_units' user.id %}">workouts</a></li>
                        <li class="sidebar-subcategory"><a href="">plans</a></li>
                    </ul>
                </li>

                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="#nutrition-subnav" data-toggle="collapse" aria-expanded="false">Nutrition</a>
                    </div>
                    <ul class="sidebar-subnav collapse" id="nutrition-subnav">
                    </ul>
                </li>

                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="#community-subnav" data-toggle="collapse" aria-expanded="false">Community</a>
                    </div>
                </li>

                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="#system-subnav" data-toggle="collapse" aria-expanded="false">system</a>
                    </div>
                    <ul class="sidebar-subnav collapse" id="system-subnav">
                        <li class="sidebar-subcategory"><a href="{% url 'profile' user.id %}">profile</a></li>
                        <li class="sidebar-subcategory"><a href="">settings</a></li>
                        <li class="sidebar-subcategory"><a href="">quit</a></li>
                    </ul>
                </li>


                <li class="sidebar-category">
                    <div class="sidebar-category-header">
                        <a href="#mockup-subnav" data-toggle="collapse" aria-expanded="false">Mock</a>
                    </div>
                    <ul class="sidebar-subnav collapse" id="mockup-subnav">
                        <li class="sidebar-subcategory"><a href="{% url 'mockup' user.id %}">Mockup</a></li>
                    </ul>
                </li>
{% endblock %}